export const routeAccess = {
  "/": [
    "ADMIN",
    "MANAGER",
    "DOCTOR",
    "NURSE",
    "MIDWIFE",
    "REGISTRAR",
    "LAB_OFFICER",
    "FINANCE_OFFICER",
    "patient",
    "sign-in",
  ],
  "/sign-in(.*)": [
    "ADMIN",
    "MANAGER",
    "DOCTOR",
    "NURSE",
    "MIDWIFE",
    "REGISTRAR",
    "LAB_OFFICER",
    "FINANCE_OFFICER",
    "patient",
    "sign-in",
  ],
  "/sign-up(.*)": [
    "ADMIN",
    "MANAGER",
    "DOCTOR",
    "NURSE",
    "MIDWIFE",
    "REGISTRAR",
    "LAB_OFFICER",
    "FINANCE_OFFICER",
    "patient",
    "sign-in",
  ],
  "/admin(.*)": ["ADMIN", "MANAGER"],
  "/doctor(.*)": ["DOCTOR", "ADMIN", "MANAGER", "NURSE"],
  "/staff(.*)": [
    "NURSE",
    "MIDWIFE",
    "REGISTRAR",
    "LAB_OFFICER",
    "FINANCE_OFFICER",
    "ADMIN",
    "MANAGER",
  ],
  "/patient-portal(.*)": ["patient"],
  "/record/users": ["ADMIN", "MANAGER"],
  "/record/doctors": ["ADMIN", "MANAGER", "REGISTRAR"],
  "/record/doctors(.*)": ["ADMIN", "MANAGER", "DOCTOR", "REGISTRAR"],
  "/record/staffs": ["ADMIN", "MANAGER"],
  "/record/patients": [
    "ADMIN",
    "MANAGER",
    "DOCTOR",
    "NURSE",
    "REGISTRAR",
    "FINANCE_OFFICER",
  ],
  "/patient/registrations": ["REGISTRAR", "ADMIN", "MANAGER", "NURSE"],
  "/billing(.*)": ["FINANCE_OFFICER", "ADMIN", "MANAGER"],
};
